name: DKEntertainment
favicon: null
layout_spectrum: 0.74708
typography_spectrum: 0.25946
title: DK Entertainment The Place To Build Your Music Career
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5df05'
    - '#68a322'
    - '#fefdff'
    - '#150000'
    - '#593e08'
  brandStrength: 0.3678767445962876
  lightness: 0.8878857460804284
  saturation: 0.5490821513812989
  rhythmicContrast: 0.017219315515831113
purpose: []
